### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by MostHated** [KinectToVR/k2vr-application#1]
Hey there,
    I was wondering if this happens to work without SteamVR? I am trying to find a way to use my Kinect along with NoloVR, but not to play a game, instead to record the motion data either in iClone (https://www.reallusion.com/iclone/mocap/default.html) or really any other application, it doesn't matter to me what app it is, I am just trying to get the data to use in animations. Is there any chance that your application might work for this?

Thanks!
-MH

**Comment by meruune** [comment]
KinectToVR is openvr-relative app and cannot work without it.
If you want to just read positions from kinect and send them somewhere,
please rather take a look at C# kinect integration.
Anyway, if you'd like to use KinectToVR in this way,
please take a look at the [current repo](https://github.com/KimihikoAkayasaki/KinectToVR) (this one's rewrite)
