### ISSUE TITLE
Downloads now marked as a trojan by Windows

### ISSUE THREAD

**Issue by lilithebowman** [KinectToVR/k2vr-application#2]
![image](https://user-images.githubusercontent.com/1637212/97319775-8f3dce80-1843-11eb-9c2e-633ce80383a3.png)

As you can see in the image above, Microsoft has marked this executable as having a trojan via AI scanning.

This is likely a false positive but I wanted to bring it to your attention. Sadly unless we pay for a publisher key, I think this will keep happening.

上の画像でわかるように、Microsoftは、AIスキャンを介してこの実行可能ファイルをトロイの木馬を持つものとしてマークしています。

これは誤検知の可能性がありますが、注意を喚起したいと思います。 残念ながら、パブリッシャーキーの支払いをしない限り、これは今後も続くと思います。

**Comment by lilithebowman** [comment]
It appears the executable DOES detect a virus under other virus scanners as well:
https://www.virustotal.com/gui/file/c4273fa29826188af4bf15c1940fb6de4ad940d026ab3ec39951af08c7833e28/detection

実行可能ファイルは、他のウイルススキャナーでもウイルスを検出するようです。

**Comment by lilithebowman** [comment]
I'm going to build my own copy of this project and see if it still reports as a virus under VirusTotal

このプロジェクトの独自のコピーを作成し、VirusTotalでウイルスとして報告されるかどうかを確認します。

**Comment by lilithebowman** [comment]
Oh no... why does this use a proprietary version of QT for Windows?

**Comment by lilithebowman** [comment]
![image](https://user-images.githubusercontent.com/1637212/97351212-d2119d80-1867-11eb-9c73-5360c76ee23d.png)
This is a bit of a nightmare to work on. I fully installed QT enterprise and I don't know how to get the QT library to be seen by VS now.

これは、取り組むには少し悪夢です。 QTエンタープライズを完全にインストールしましたが、QTライブラリをVSに表示させる方法がわかりません。

**Comment by meruune** [comment]
@lilithebowman 
Did you set up Qt plugin for Visual Studio?
Also, installer is (was) recognized as a virus, not app itself.

**Comment by meruune** [comment]
It appears you have posted screenshot of installer being recognized as a virus,
but the current repo's actually main application rewrite.
You have also cloned work-on application project and not the installer.
Please double-check next time before posting such an issue.

**Comment by lilithebowman** [comment]
It's not invalid.

You're telling me it doesn't concern you at all that the installer is marked as a trojan by two different services?

Also: yes I installed QT.

My goal was to try to compile the project for myself.

無効ではありません。

インストーラーが2つの異なるサービスによってトロイの木馬としてマークされていることは、まったく問題ではないと言っていますか？

また：はい、QTをインストールしました。

私の目標は、自分でプロジェクトをコンパイルすることでした。

**Comment by lilithebowman** [comment]
That was the most heads baffling reply to wake up to.

What... The actual f___?

**Comment by lilithebowman** [comment]
Please extract head from a$$ before responding to issues.

**Comment by lilithebowman** [comment]
> "Did you set up Qt plugin for Visual Studio?"

Are you having trouble reading my issue post? I assume you're in Japan right?

QT開発者キットをインストールしましたが、QTプラグインについて知りません。

QTプラグインをインストールするにはどうすればよいですか？

**Comment by meruune** [comment]
> You're telling me it doesn't concern you at all that the installer is marked as a trojan by two different services?

No, I'm not.
I'm just informing you that you have posted issue in wrong repository,
not connected with actual installer and it being recognized as a virus.
For knowing why it's being so, feel free to contact @TripingPC 

E: The issue about installer being recognized as a virus is invalid for the application itself. What do those 2 have to do with each other? Please post issue on correct repo next time or just join discord and ask. 
Also this
> Please extract head from a$$ before responding to issues.

So do you.
Who do you think you are? Please read where do you post issues and what do they relate to. (↑: issue is definitely related to installer and not the app, also any binaries haven't been released for the new version so how could you check?)

For setting up the project... I'll just add build instructions to readme.

**Comment by lilithebowman** [comment]
Thank you so much!

That would be a huge help!
